import requests
import os
import random
import string
import json

#dette kan brukes til å lage random passord under. men ikke egt nødvendig.
chars = string.ascii_letters + string.digits + '!@#$%^&*()'
random.seed = (os.urandom(1024))

#dette er urls vi skal sende post data til.
url = 'http://www.it.hiof.no/~tomhnatt/sikkerhet/saveaccount.php'

#her er en liste med de beste navnene som er.(bare å google en navneliste også for den sags skyld.)
names = [
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter",
  "walter"
]

 #for hveert navn i navn, så kjører vi en fake login.
for name in names:
	name_extra = ''.join(random.choice(string.digits))

    #her kan man putte det man ønsker selv så klart. dette er det som vlir sendt.
	username = name.lower() + name_extra + ' ez pwn'
	password = 'lmao n1'
    email = username + '@gmail.com'

    #under er dataeen man sender til serveren. her må data kategoriene stemme med form-data som chrome viste.
    #vi sier ogsså at man ikke skal gå til neste side etter å ha logget inn. slik at den kan kjøre på nytt.
	requests.post(url, allow_redirects=False, data={
        'name': username,
        'email': email,
        'un': password,
        'pw': password,
		'feidename': username,
	})
